server:
  port: 9001
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 4
      worker: 32
#  servlet:
#    context-path: /${spring.application.name}

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: dows-store
  profiles:
    include: mysql,mybatis,mvc,redis
    active: sit
#debug: true
